version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./path/config:/config
      - ./path/tvseries:/data/tvshows
      - ./path/movies:/data/movies
      - ./path/fonts/:/usr/share/fonts/truetype/dejavu
      - /mnt:/mnt
    ports:
      - 8059:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
